### ISSUE TITLE
Add secret customisation menu

### ISSUE THREAD

**Issue by damavrom** [damavrom/Important-Sound#2]
A menu that will become visible only when the user presses a specific button or clicks at a specific place, that will allow them to customise the parameters of the sound. 
There may also be a warning that by customising the parameters of the sound, the importance of the sound can be effected negatively.

**Comment by ghost** [comment]
I was disappointed by the lack of a secret menu. Definitely would remove my star if the sound was any less important though.

**Comment by damavrom** [comment]
Okay, the task has been completed, please keep the stars where they are. This thread will be closed indefinetely. Goodbye.
